spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true


---
spring:
  profiles: cloud

---
