name:
  localWebUI

server.port:
  8080
spring.application.name:
  webui

eureka.instance.instance-id:
  ${spring.application.name}:${random.value}

#debug: true
#trace: true
#logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
#logging.level.org.springframework: TRACE
#logging.level.reactor: debug
spring.http.log-request-details: true
logging.level.org.springframework.web: TRACE
logging.level.org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <client-id>
            client-secret: <client-secret>
          github:
            client-id: <client-id>
            client-secret: <client-secret>



      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
#        provider:
#          auth-server:

